channels:
  - conda-forge
  - bioconda
  - eclarke
  - louiejtaylor
dependencies:
  - snakemake=5.5.0
  - ruamel.yaml
  - biopython
  - trimmomatic=0.36
  - fastqc
  - blast
  - kraken2
  - kraken-biom
  - vsearch
  - cutadapt
  - bwa>=0.7.17
  - pysam
  - pandas
  - megahit<1.2
  - prodigal
  - semantic_version
  - setuptools_scm
  - komplexity=0.3.6
  - rust-bio-tools
  - grabseqs=0.6.0
  - minimap2
  - multiqc
  - h5py # temp: patching missing dependency of biom-format (req'd by kraken-biom)
  - samtools>=1.9
  - bcftools>=1.9
  - git
