suffix: qc
# Trimmomatic
trimmomatic_fp:
  "/media/8TB_PLAYGROUND/home/tanesc/software/Trimmomatic-0.33/trimmomatic-0.33.jar"
adapter_fp:
  "/media/8TB_PLAYGROUND/home/tanesc/software/Trimmomatic-0.33/adapters/NexteraPE-PE.fa"
java_heapsize: 512M
leading: 3
trailing: 3
slidingwindow: [4,15]
minlen: 36
# decontam
decontam_cfg_fp:
  "/media/8TB_PLAYGROUND/home/tanesc/.decontam_human.json"
host: 'human'
pct_id: 0.5 # percent identity
frac: 0.6   # fraction of alignment len
keep_sam: True
